HospitalAppointmentSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('appointment.urls')),
]

appointment/urls.py
from django.urls import path
from .views import (
	index,
	profile,
	sign_up,
	logout_view,
	choose_city,
	choose_county,
	choose_hospital,
	choose_polyclinic,
	choose_doctor,
	make_an_appointment
)

app_name = 'appointment'

urlpatterns=[
	path('', index, name='index'),
	path('profile', profile, name='profile'),
	path('signup/',sign_up,name='sign_up'),
	path('logout',logout_view,name='logout'),
	path('choose_city/', choose_city, name='choose_city'),
	path('<int:cityPk>/choose_county/', choose_county, name='choose_county'),
	path('<int:countyPk>/choose_hospital/', choose_hospital, name='choose_hospital'),
	path('<int:hospitalPk>/choose_polyclinic/', choose_polyclinic, name='choose_polyclinic'),
	path('<int:polyclinicPk>/choose_doctor/', choose_doctor, name='choose_doctor'),
	path('<int:doctorPk>/make_an_appointment/', make_an_appointment, name='make_an_appointment'),
]

appointment/forms.py
from django import forms
from .models import *
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
import datetime

class PatientForm(forms.ModelForm):
	first_name = forms.CharField(
		max_length = 150,
		widget = forms.TextInput(
			attrs={
				"class" : "textbox",
				"placeholder" : "First Name",
			}
		)
	)
	last_name = forms.CharField(
		max_length = 150,
		widget = forms.TextInput(
			attrs={
				"class" : "textbox",
				"placeholder" : "Last Name",
			}
		)
	)

	email = forms.EmailField(
		widget = forms.EmailInput(
			attrs={
				"class" : "textbox",
				"placeholder" : "username@example.com",
			}
		)
	)

	password = forms.CharField(
		widget = forms.PasswordInput(
			attrs = {
				"class" : "textbox",
				"placeholder" : "Password",
			}
		)
	)

	class Meta:
		"""Meta definition for Patientform."""

		model = Patient
		exclude = (
			'user',
		)
		widgets = {
			"identification_number": forms.TextInput(
				attrs={
					"class" : "textbox",
					"placeholder" : "Identification Number",
					"max_length" : 11
				}
			),
			"birth_place": forms.Select(
				attrs={
					"class" : "textbox",
				}
			),
			"birth_date": forms.DateInput(
				attrs={
					"class" : "textbox",
					"type" : "date"
				}
			),
			"father_name": forms.TextInput(
				attrs={
					"class" : "textbox",
					"placeholder" : "Father Name",
					"max_length" : 15
				}
			),
			"mother_name": forms.TextInput(
				attrs={
					"class" : "textbox",
					"placeholder" : "Mother Name",
					"max_length" : 15
				}
			),
			"phone_number": forms.TextInput(
				attrs={
					"class" : "textbox",
					"placeholder" : "Phone Number",
					"max_length" : 20
				}
			),
			"blood_group": forms.Select(
				attrs={
					"class" : "textbox",
				}
			),
			"gender": forms.Select(
				attrs={
					"class" : "textbox",
				}
			),
		}


class CityForm(forms.Form):
	city = forms.ModelChoiceField(
		queryset=City.objects.all(),
		widget=forms.Select(
			attrs={
				"class" : "form-control"
			}
		)
	)

class CountyForm(forms.Form):
	
	def __init__(self,*args,**kwargs):
		city = kwargs.pop('city')
		counties = County.objects.filter(city = city)
		super(CountyForm, self).__init__(*args,**kwargs)
		self.fields['county'] = forms.ModelChoiceField(queryset = counties)
		self.fields['county'].widget.attrs.update({'class':'form-control'})


class HospitalForm(forms.Form):
	
	def __init__(self,*args,**kwargs):
		county = kwargs.pop('county')
		hospitals = Hospital.objects.filter(county = county)
		super(HospitalForm, self).__init__(*args,**kwargs)
		self.fields['hospital'] = forms.ModelChoiceField(queryset=hospitals)
		self.fields['hospital'].widget.attrs.update({'class':'form-control'})

class PolyclinicForm(forms.Form):
	
	def __init__(self,*args,**kwargs):
		hospital = kwargs.pop('hospital')
		polyclinics = Polyclinic.objects.filter(hospital = hospital)
		super(PolyclinicForm, self).__init__(*args,**kwargs)
		self.fields['polyclinic'] = forms.ModelChoiceField(queryset = polyclinics)
		self.fields['polyclinic'].widget.attrs.update({'class':'form-control'})

class DoctorForm(forms.Form):
	
	def __init__(self,*args,**kwargs):
		polyclinic = kwargs.pop('polyclinic')
		doctors = Doctor.objects.filter(polyclinic = polyclinic)
		super(DoctorForm, self).__init__(*args,**kwargs)
		self.fields['doctor'] = forms.ModelChoiceField(queryset=doctors)
		self.fields['doctor'].widget.attrs.update({'class':'form-control'})

# class AppointmentForm(forms.Form):
# 	date = forms.DateField(
# 		initial = datetime.date.today,
# 		label = "Appointment Date"
# 	)
# 	time = forms.TimeField(
# 		widget = forms.TimeInput(
# 			format = '%H:%M',
# 		),
# 		label = "Appointment Time",
# 		initial = datetime.datetime.now().strftime('%H:%M:%S')
# 	)


# class LoginForm(forms.Form):
# 	username = forms.CharField()
# 	password = forms.CharField(widget=forms.PasswordInput)

# 	def clean(self):
# 		username=self.cleaned_data.get('username')
# 		password=self.cleaned_data.get('password')
# 		if username and password:
# 			user = authenticate(username=username,password=password)
# 			if not user:
# 				raise forms.ValidationError('Kullanıcı adını veya parolayı yanlış girdiniz!')
# 		return super(LoginForm,self).clean()

# class ChangePassForm(forms.Form):
	
# 	old_password=forms.CharField()
# 	new_password=forms.CharField()
# 	again_new_pass=forms.CharField()

# 	def __init__(self,*args,**kwargs):
# 		user=kwargs.pop('user')
# 		super(ChangePassForm,self).__init__(*args,**kwargs)
# 		self.user=user
# 		self.fields['old_password'].widget = forms.PasswordInput()
# 		self.fields['new_password'].widget = forms.PasswordInput()
# 		self.fields['again_new_pass'].widget = forms.PasswordInput()
	
# 	def clean(self):
# 		old_password = self.cleaned_data.get('old_password')
# 		if not self.user.check_password(old_password):
# 			raise forms.ValidationError('Eski şifrenizi yanlış girdiniz!')
# 		return super(ChangePassForm,self).clean()

# class SigninForm(forms.ModelForm):
	
# 	class Meta:
# 		model=Patients
# 		exclude=[]

# 	def __init__(self,*args,**kwargs):
# 		super(SigninForm, self).__init__(*args,**kwargs)
# 		CHOICES=[('Bay','Bay'),('Bayan','Bayan')]
# 		BloodGroups=[
# 					('0 Rh-','0 Rh-'),('0 Rh+','0 Rh+'),
# 					('A Rh-','A Rh-'),('A Rh+','A Rh+'),
# 					('B Rh-','B Rh-'),('B Rh+','B Rh+'),
# 					('AB Rh-','AB Rh-'),('AB Rh+','AB Rh+'),
# 					]
# 		self.fields['gender_of_patient'].widget = forms.widgets.RadioSelect(choices=CHOICES)
# 		self.fields['patient_tc_no'] = forms.CharField(max_length=11)
# 		self.fields['patient_name'] = forms.CharField(max_length=25)
# 		self.fields['patient_surname'] = forms.CharField(max_length=25)
# 		self.fields['blood_group_of_patient']=forms.ChoiceField(choices=BloodGroups)
# 		self.fields['mother_name_of_patient'] = forms.CharField(max_length=15)
# 		self.fields['father_name_of_patient'] = forms.CharField(max_length=15)
# 		self.fields['telephone_of_patient'] = forms.CharField(max_length=15)
# 		self.fields['e_mail_of_patient'] = forms.CharField(max_length=25)
# 		self.fields['patient_place_of_birth'] = forms.CharField(max_length=15)
# 		self.fields['patient_date_of_birth'] = forms.DateField(initial=datetime.date.today)
# 		self.fields['password_of_patient'] = forms.CharField(max_length=25)

# class ChooseCityForm(forms.Form):
	
# 	def __init__(self,*args,**kwargs):
# 		super(ChooseCityForm, self).__init__(*args,**kwargs)
# 		self.fields['city_name'] = forms.ModelChoiceField(queryset=City.objects.annotate())
# 		self.fields['city_name'].widget.attrs.update({'class':'form-control'})

# class ChooseCountyForm(forms.Form):
	
# 	def __init__(self,*args,**kwargs):
# 		city = kwargs.pop('city')
# 		counties = County.objects.filter(city_of_county = city)
# 		super(ChooseCountyForm, self).__init__(*args,**kwargs)
# 		self.fields['county_name'] = forms.ModelChoiceField(queryset=counties.annotate())
# 		self.fields['county_name'].widget.attrs.update({'class':'form-control'})

# class ChooseHospitalForm(forms.Form):
	
# 	def __init__(self,*args,**kwargs):
# 		county = kwargs.pop('county')
# 		hospitals = Hospitals.objects.filter(county_of_hospital = county)
# 		super(ChooseHospitalForm, self).__init__(*args,**kwargs)
# 		self.fields['hospital_name'] = forms.ModelChoiceField(queryset=hospitals.annotate())
# 		self.fields['hospital_name'].widget.attrs.update({'class':'form-control'})


# class ChoosePolyclinicForm(forms.Form):
	
# 	def __init__(self,*args,**kwargs):
# 		hospital = kwargs.pop('hospital')
# 		polyclinics = Polyclinics.objects.filter(hospital_of_polyclinic = hospital)
# 		super(ChoosePolyclinicForm, self).__init__(*args,**kwargs)
# 		self.fields['polyclinic_name'] = forms.ModelChoiceField(queryset=polyclinics.annotate())
# 		self.fields['polyclinic_name'].widget.attrs.update({'class':'form-control'})


# class ChooseDrForm(forms.Form):
	
# 	def __init__(self,*args,**kwargs):
# 		polyclinic = kwargs.pop('polyclinic')
# 		doctors = Doctors.objects.filter(polyclinic_of_doctor = polyclinic)
# 		super(ChooseDrForm, self).__init__(*args,**kwargs)
# 		self.fields['dr_name'] = forms.ModelChoiceField(queryset=doctors.annotate())
# 		self.fields['dr_name'].widget.attrs.update({'class':'form-control'})


# class GetAppointmentForm(forms.Form):

# 	def __init__(self,*args,**kwargs):
# 		super(GetAppointmentForm,self).__init__(*args,**kwargs)
# 		self.fields['date_of_appointment'] = forms.DateField(initial=datetime.date.today,label="Randevu Tarihi")
# 		self.fields['begin_time_of_appointment'] = forms.TimeField(widget=forms.TimeInput(format='%H:%M'),label="Randevu Saati",initial=datetime.datetime.now().strftime('%H:%M:%S'))

appointment/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from django.contrib.auth import (
	authenticate,
	login,
	logout,
	update_session_auth_hash
)
from django.contrib.auth.models import User
from django.contrib.auth.forms import(
	AuthenticationForm,
	PasswordChangeForm,
	UserCreationForm

)
from django.contrib import messages

from .models import *
from .forms import *

def index(request):
	form = AuthenticationForm(data = request.POST or None)
	if form.is_valid():
		username=form.cleaned_data.get('username')
		password=form.cleaned_data.get('password')
		user=authenticate(username=username,password=password)
		if user is not None:
			login(request, user)
			return redirect('appointment:profile')
	return render(request,'appointment/login.html',{'form':form})

@login_required(login_url = "appointment:index")
def profile(request):
	patient = Patient.objects.get(identification_number = request.user.username)
	appointments = Appointment.objects.filter(patient = patient)
	form = PasswordChangeForm(request.user, request.POST or None)
	context = {
		"patient" : patient,
		"appointments" : appointments,
		"form" : form
	}
	if form.is_valid():
		user = form.save()
		update_session_auth_hash(request, user)
		messages.success(request, 'Your password was successfully updated!')
		return redirect('appointment:profile')
	return render(request,'appointment/profile.html', context)

def logout_view(request):
	logout(request)
	return redirect('appointment:index')

def sign_up(request):
	form = PatientForm(request.POST or None)
	context = {
		"form" : form,
	}
	if form.is_valid():
		patient = form.save(commit = False)
		user = User.objects.create(
			username = patient.identification_number,
			first_name = form.cleaned_data.get("first_name"),
			last_name = form.cleaned_data.get("last_name"),
			email = form.cleaned_data.get("email")
		)
		user.set_password(form.cleaned_data.get("password"))
		user.save()
		patient.user = user
		patient.save()
		return redirect("appointment:index")
	return render(request, 'appointment/sign_up.html', context)

@login_required(login_url = "appointment:index")
def choose_city(request):
	form = CityForm(request.POST or None)
	context = {
		"form" : form
	}
	if form.is_valid():
		city = form.cleaned_data.get("city")
		return redirect('appointment:choose_county', cityPk = city.pk)
	return render(request,'appointment/choose_city.html', context)

@login_required(login_url = "appointment:index")
def choose_county(request, cityPk):
	city = City.objects.get(pk = cityPk)
	form = CountyForm(request.POST or None, city = city)
	context = {
		"form" : form,
		"city" : city,
	}
	if form.is_valid():
		county = form.cleaned_data.get('county')
		return redirect('appointment:choose_hospital', countyPk = county.pk)
	return render(request, 'appointment/choose_county.html', context)

@login_required(login_url = "appointment:index")
def choose_hospital(request, countyPk):
	county = County.objects.get(pk = countyPk)
	city = City.objects.get(pk = county.city.pk)
	form = HospitalForm(request.POST or None, county = county)
	context = {
		"form" : form,
		"city" : city,
		"county" : county,
	}
	if form.is_valid():
		hospital = form.cleaned_data.get('hospital')
		return redirect('appointment:choose_polyclinic', hospitalPk = hospital.pk)
	return render(request,'appointment/choose_hospital.html', context)

@login_required(login_url = "appointment:index")
def choose_polyclinic(request, hospitalPk):
	hospital = Hospital.objects.get(pk = hospitalPk)
	form = PolyclinicForm(request.POST or None, hospital = hospital)
	context = {
		"form" : form,
		"hospital" : hospital
	}
	if form.is_valid():
		polyclinic = form.cleaned_data.get('polyclinic')
		return redirect('appointment:choose_doctor', polyclinicPk = polyclinic.pk)
	return render(request, 'appointment/choose_polyclinic.html', context)

def choose_doctor(request, polyclinicPk):
	polyclinic = Polyclinic.objects.get(pk = polyclinicPk)
	form = DoctorForm(request.POST or None, polyclinic=polyclinic)
	context = {
		"form": form,
		"polyclinic" : polyclinic
	}
	if form.is_valid():
		doctor = form.cleaned_data.get('doctor')
		return redirect('appointment:make_an_appointment', doctorPk = doctor.pk)
	return render(request,'appointment/choose_doctor.html', context)

def make_an_appointment(request, doctorPk):
	doctor = Doctor.objects.get(pk = doctorPk)
	context = {
		"doctor" : doctor
	}
	if request.method == "POST":
		date = request.POST['date']
		time = request.POST['time']
		patient = Patient.objects.get(user = request.user)
		Appointment.objects.create(
			date = f"{date} {time}",
			doctor = doctor,
			patient = patient
		)
		messages.success(request, "Making Appointment Successfully Completed!")
		return redirect('appointment:profile')
	return render(request,'appointment/make_an_appointment.html', context)

appointment/templates/appointment/choose_city.html
{% load static %}
<!DOCTYPE html>
<head>
	<meta charset="UTF-8" lang='tr'>
	<title>City Choice</title>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Laila" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.js"></script>
	<link rel="stylesheet" href="{% static 'css/sign-in.css' %}">
</head>
<body>
{% if user.is_authenticated %}
	<div class="container">
		<h1 style="text-align: center;color: orange;font-weight: bold">{{user.first_name}} {{user.last_name}}</h1>
		<h1 style="text-align: center;">Choose City</h1><br>
		<form style="text-align: center" action="" method="POST">{% csrf_token %}
			<div style="text-align: center;">
				<br>
		    	{{form.city}}
				<br>
			</div>
		    <input type="submit" value="Next" class = "btn btn-dark" style="width: 100px;">
			<br>
			<a href="{% url 'appointment:profile' %}" class="btn btn-dark" style="width: 200px; margin-top: 25px;">Homepage</a>
		</form>
	</div>
{% else %}
    <div style=" margin-top: 15%">
        <h1 style="text-align: center;">You must be logged in</h1>
        <input style="margin-right: 44%" onclick="window.location.href='{% url 'appointment:index' %}'" type="button" class="btn btn-danger appointment" value="Click to Login">
    </div>
{% endif %}
</body>
</html>

appointment/templates/appointment/choose_county.html
{% load static %}
<!DOCTYPE html>
<head>
	<meta charset="UTF-8" lang='tr'>
	<title>County Choice</title>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Laila" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.js"></script>
	<link rel="stylesheet" href="{% static 'css/sign-in.css' %}">
</head>
<body>
{% if user.is_authenticated %}
	<div class="container">
		<h1 style="text-align: center;color: orange;font-weight: bold">{{user.first_name}} {{user.last_name}}</h1>
		<h1 style="text-align: center;">Choose County</h1><br>
		<h4 style="text-align: left;color: #35041c;font-weight: bold">{{city.name}}</h4>
		<form style="text-align: center" action="" method="POST">{% csrf_token %}
			<div style="text-align: center;">
				<br>
		    	{{form.county}}
				<br>
			</div>
			<a href="{% url 'appointment:choose_city'  %}" class="btn btn-dark" style="width: 100px;">Back</a>
		    <input type="submit" value="Next" class = "btn btn-dark" style="width: 100px;">
			<br>
			<a href="{% url 'appointment:profile' %}" class="btn btn-dark" style="width: 200px; margin-top: 25px;">Homepage</a>
		</form>
	</div>
{% else %}
  <div style=" margin-top: 15%">
          <h1 style="text-align: center;">You must be logged in</h1>
          <input style="margin-right: 44%" onclick="window.location.href='{% url 'appointment:index' %}'" type="button" class="btn btn-danger appointment" value="Click to Login">
  </div>
{% endif %}
</body>
</html>

appointment/templates/appointment/profile.html
{% load static %}
<!DOCTYPE html>
<head>
	<meta charset="UTF-8" lang="tr">
	<title>Profil</title>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<link href="https://fonts.googleapis.com/css?family=Laila" rel="stylesheet">
	<link rel="stylesheet" href=" {% static 'css/profil.css'  %}">
</head>
<body>
	<div class="container">
		<h1>{{ user.username }}</h1>
		<div class="card">
			<div class="personal">
				<figure>
					<img src="http://lorempixel.com/400/200/" alt="">
				</figure>
				<h3 class="name">{{ user.first_name }} {{ user.last_name }}</h3>
			</div>
			<ul class="options">
				<li><button class="appointment" onclick="window.location.href={% url 'appointment:choose_city' %}">Make an Appointment</button></li>
				<li><button class="history" data-toggle="modal" data-target="#myHistory">Appointment History</button>
					<div class="modal fade" id="myHistory" role="dialog">
						<div class="modal-dialog modal-lg">
							<div class="modal-content">
								<div class="modal-header">
									<h5>Appointment History</h5>
									<button type="button" class="close" data-dismiss="modal">&times;</button>
								</div>
								<div class="modal-body ">
									<table class="table">
										<thead>
											<tr>
												<th class="hastane" scope="col">Hastane</th>
												<th class="poliklinik" scope="col">Poliklinik</th>
												<th class="doktor" scope="col">Doktor</th>
												<th class="tarih" scope="col">Tarih</th>
											</tr>
										</thead>
										<tbody>
											{% for appointment in appointments %}
											<tr>
												<td>{{ appointment.doctor.polyclinic.hospital.name }}</td>
												<td>{{ appointment.doctor.polyclinic.name }}</td>
												<td>{{ appointment.doctor.first_name }} {{ appointment.doctor.last_name }}</td>
												<td>{{ appointment.date }}</td>
											</tr>
											{% endfor %}
										</tbody>
									</table>
								</div>
								<div class="modal-footer">
									<button class="btn btn-danger historyexit" data-dismiss="modal">Close</button>
								</div>
							</div>
						</div>
					</div>
				</li>
				<li><button class="pass" data-toggle="modal" data-target="#myModal">Change Password</button>
					<div class="modal fade" id="myModal" role="dialog">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<h5>Change Password</h5>
									<button type="button" class="close" data-dismiss="modal">&times;</button>
								</div>
								<form action="" method="POST"> {% csrf_token %}
									<div class="modal-body">
										<input id="old_password" name="old_password" class="textbox" onfocus="this.value=''" type="password" placeholder="Old Password" required>
										<input id="password" name="new_password1" class="textbox" onfocus="this.value=''" type="password" placeholder="New Password" required>
										<input id="confirm_password" name="new_password2" class="textbox" onfocus="this.value=''" type="password" placeholder="Confirm New Password" required>
									</div>
									<div class="modal-footer">
										<input type="submit" class="btn btn-danger kaydet" id="kaydet" value="Confirm">
									</div>
								</form>
							</div>
						</div>
					</div>
				</li>
				<li><button class="exit" onclick="window.location.href='{% url 'appointment:logout' %}'">Logout</button></li>
			</ul>
			<h3 style="color:red">
				{% if form.errors %}
					{{ form.non_field_errors}}
				{% endif %}
			</h3>
			<h3 style = "color:green">
				{% if messages %}
					{% for i in messages%}
						{{ i }}
					{% endfor %}
				{% endif %}
			</h3>
		</div>
	</div>
<script>
	$('.kaydet').click(function(event){
	    data = $('#password').val();
	    var len = data.length;
	    if($('#password').val() != $('#confirm_password').val()) {
	        alert("Yeni parolanizi tekrar giriniz");
					$('#confirm_password').css("background-color","#dd0000");
					$('#confirm_password').css("color","white");
	        event.preventDefault();
	    }
	});
</script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

appointment/templates/appointment/sign_up.html
{% load static %}
<!DOCTYPE html>
	<head>
		<meta charset="UTF-8">
		<title>Sign Up</title>
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'css/sign-up.css' %}">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.js"></script>
		<script src="{% static 'js/jquery.inputmask.bundle.js' %}"></script>
	</head>
	<body>
		<div class="container">
			<h1>Appointment System Sign Up Form</h1>
			<div class="sign-up">
				<form method="POST"> {% csrf_token %}
					{{ form.as_p }}
					<input class="kaydol-button"  type="submit" value="Sign Up" >
				</form>
			</div>
		</div>
	</body>
</html>